//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xl2cad {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xl2cad.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2009/07/customui&apos;&gt;
        ///      &lt;ribbon&gt;
        ///        &lt;tabs&gt;
        ///          &lt;tab id=&quot;xl2cad&quot; label=&quot;XL2CAD&quot;&gt;
        ///            &lt;group id=&quot;xl2cad&quot; label=&quot;XL2CAD&quot;&gt;
        ///              &lt;button id=&quot;button1&quot; label=&quot;导入CAD&quot; onAction=&quot;OnButton1Pressed&quot;/&gt;
        ///			  &lt;button id=&quot;button2&quot; label=&quot;CAD导出&quot; onAction=&quot;OnButton2Pressed&quot;/&gt;
        ///            &lt;/group &gt;
        ///          &lt;/tab&gt;
        ///        &lt;/tabs&gt;
        ///      &lt;/ribbon&gt;
        ///    &lt;/customUI&gt; 的本地化字符串。
        /// </summary>
        public static string RibbonXML {
            get {
                return ResourceManager.GetString("RibbonXML", resourceCulture);
            }
        }
    }
}
